# This is a basic workflow to help you get started with Actions

name: Deploy gcp


on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:

env:
  #PROJECT_ID: ${{ secrets.PROJECT_ID_GCP }}
  #GCE_INSTANCE_ZONE: us-east1-d
  GCE_INSTANCE_ZONE: us-east1-b

jobs:

  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      #- name: Checkout the code # obtiene el repositorio
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        #run: mvn clean package -Dmaven.test.skip=true
        run: mvn clean package

        #Test coverage
      - name: Add coverage codecov
        uses: codecov/codecov-action@v2
        with:
          #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ${{ github.workspace }}/target/site/jacoco
          files: jacoco.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
#      - name: Add coverage to PR
#        id: jacoco
#        uses: madrapps/jacoco-report@v1.2
#        with:
#          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
#          token: ${{ secrets.TOKEN_GITHUB_JACOCO }}
#          min-coverage-overall: 40
#          min-coverage-changed-files: 60

#      - name: Login github
#        uses: actions/labeler@v4 # validar que si sea para login con github
#        with:
#          repo-token: ${{ secrets.TOKEN_GITHUB_JACOCO }}
#
#      # generates coverage-report.md and publishes as checkrun
#      - name: JaCoCo Code Coverage Report
#        id: jacoco_reporter
#        uses: PavanMudigonda/jacoco-reporter@v4.3
#        with:
#          coverage_results_path: target/site/jacoco/jacoco.xml
#          coverage_report_name: Coverage
#          coverage_report_title: JaCoCo
#          github_token: ${{ secrets.TOKEN_GITHUB_JACOCO }}
#          skip_check_run: false
#          minimum_coverage: 80
#          fail_below_threshold: true
#          publish_only_summary: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.KEY_SECRET_GCP }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=gcr.io/${{ secrets.PROJECT_ID_GCP }}/modyo:latest
          cache-to: type=inline
          tags: gcr.io/${{ secrets.PROJECT_ID_GCP }}/modyo:latest

      - name: Deploy cloud run
        run: |-
             gcloud run deploy modyo \
             --image=gcr.io/${{ secrets.PROJECT_ID_GCP }}/modyo \
             --project=${{ secrets.PROJECT_ID_GCP }} \
             --region=us-central1 \
              && gcloud config set run/region us-central1 \
              && gcloud run services update-traffic modyo --to-latest