# This is a basic workflow to help you get started with Actions

name: CI


on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:

env:
  #PROJECT_ID: ${{ secrets.PROJECT_ID_GCP }}
  GCE_INSTANCE_ZONE: us-east1-d

jobs:

  ci:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      #- name: Checkout the code # obtiene el repositorio
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.KEY_SECRET_GCP }}
          project_id: ${{ secrets.PROJECT_ID_GCP }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=gcr.io/${{ secrets.PROJECT_ID_GCP }}/modyo:latest
          cache-to: type=inline
          tags: gcr.io/${{ secrets.PROJECT_ID_GCP }}/modyo:latest
          #tags: giovanny96/modyo:latest

      - name: Deploy GCE
        run: |-
            gcloud compute instances update-container "modyo" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image gcr.io/${{ secrets.PROJECT_ID_GCP }}/modyo:latest
